import { build } from 'esbuild';
import { mkdir, copyFile } from 'node:fs/promises';

await build({
  entryPoints: ['src/bootstrap.ts'],
  bundle: true,
  format: 'iife',
  target: 'firefox115',
  outfile: 'bootstrap.js',
  banner: { js: '/* Generated by esbuild. Do not edit directly. */' },
});

await mkdir('assets', { recursive: true });
await copyFile('C:/Windows/Fonts/NotoSansSC-VF.ttf', 'assets/NotoSansSC-VF.ttf');
await copyFile('src/prefs.xhtml', 'prefs.xhtml');
